dist: xenial   # required for Python >= 3.7
language: python

before_install:
  - pip install behave
  - rvm install 2.5
  - rvm use 2.5
  - gem install hiptest-publisher
  
script:
 - behave --format json -o results/results.json

after_script:
 - hiptest-publisher -c behave.conf --push=results/results.json --test-run-id=288962 --push-format=junit